### ISSUE TITLE
Kramdown upgrade need approval

### ISSUE THREAD

**Issue by Fdev210** [Fdev210/reviewing-a-pull-request#7]
@githubteacher @brianamarie @hectorsector @snyk-bot 
Hey team ! 😃 👋🏼 

I need some hand here. 🖐🏼 

My dependabot alert required me an upgrade in kramdown, from 2.3.0 to 2.3.1 cause it coudn't update by itself to latest non-vulnerable dependacies and that a high severity risk. I create a new branch and commited the alteration as oriented and requested a _pull request_. Now I need colaborator-members approve it as to make it part of the main and so be permanently.
 
Could anyone of you please reserve a little time to do this, please. In doing so the repo will be safe for all of us !

Thank you very much 🙏🏼 ❗  I appreciate it very much 🙌🏼 

🙌🏼 Happy coding 👨🏼‍💻 👩🏼‍💻

**Comment by brianamarie** [comment]
Hi @Fdev210 👋🏻 It sounds like you have branch protection enabled, requiring reviews from collaborators. You can change this by going to the "settings" tab in your repo, then going to "branches" on the left side navigation. From there, you can delete the branch protection, which will allow you to merge the pull request.

**Comment by Fdev210** [comment]
aah 😅, So was this !
🙏🏼  Thank you very much @brianamarie 🙏🏼 . I did as you instructed me and now everything looks fine again. 🥳 
You were very supportive in helping me with this issue. I appreciate that.
Here, take this flower 🌷 

regards !
